name: 定时推送

on:
  schedule:
    - cron: '0 0 8 1 * ?'   #Runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run start.sh
        run: |
          bash ./start.sh